import type { ShapeNode } from "../components";

export const TREE = [
  {
    type: "group",
    props: { width: 120, height: 180, depth: 120 },
    children: [
      // Root system
      {
        type: "shape",
        props: {
          color: "#654321",
          sides: 8,
          width: 27,
          height: 5,
          depth: 27,
          z: -2,
          topWidth: 21,
          topDepth: 21,
        },
      },
      {
        type: "shape",
        props: {
          color: "#5D3A1A",
          sides: 6,
          width: 21,
          height: 4,
          depth: 21,
          z: 2,
          topWidth: 18,
          topDepth: 18,
        },
      },

      // Main trunk - multiple segments for organic feel
      {
        type: "shape",
        props: {
          color: "#8B4513",
          sides: 12,
          width: 19,
          height: 17,
          depth: 19,
          z: 6,
          topWidth: 17,
          topDepth: 17,
          rotateY: 5,
        },
      },
      {
        type: "shape",
        props: {
          color: "#A0522D",
          sides: 12,
          width: 18,
          height: 20,
          depth: 18,
          z: 20,
          topWidth: 15,
          topDepth: 15,
          rotateY: -8,
        },
      },
      {
        type: "shape",
        props: {
          color: "#8B4513",
          sides: 10,
          width: 16,
          height: 23,
          depth: 16,
          z: 37,
          topWidth: 13,
          topDepth: 13,
          rotateY: 12,
        },
      },
      {
        type: "shape",
        props: {
          color: "#A0522D",
          sides: 10,
          width: 14,
          height: 17,
          depth: 14,
          z: 58,
          topWidth: 11,
          topDepth: 11,
        },
      },

      // Extra bark pieces to fill gaps
      {
        type: "shape",
        props: {
          color: "#654321",
          sides: 8,
          width: 16,
          height: 8,
          depth: 16,
          z: 16,
          topWidth: 15,
          topDepth: 15,
          rotateY: 15,
        },
      },
      {
        type: "shape",
        props: {
          color: "#8B4513",
          sides: 10,
          width: 14,
          height: 6,
          depth: 14,
          z: 33,
          topWidth: 13,
          topDepth: 13,
          rotateY: -10,
        },
      },
      {
        type: "shape",
        props: {
          color: "#654321",
          sides: 8,
          width: 12,
          height: 5,
          depth: 12,
          z: 53,
          topWidth: 11,
          topDepth: 11,
          rotateY: 8,
        },
      },

      // Branch extensions
      {
        type: "shape",
        props: {
          color: "#654321",
          sides: 8,
          width: 7,
          height: 12,
          depth: 7,
          x: 9,
          y: -5,
          z: 54,
          topWidth: 5,
          topDepth: 5,
          rotateX: 25,
          rotateY: 45,
          rotateZ: -15,
        },
      },
      {
        type: "shape",
        props: {
          color: "#654321",
          sides: 8,
          width: 6,
          height: 11,
          depth: 6,
          x: -7,
          y: 6,
          z: 57,
          topWidth: 4,
          topDepth: 4,
          rotateX: -20,
          rotateY: -35,
          rotateZ: 10,
        },
      },
      {
        type: "shape",
        props: {
          color: "#654321",
          sides: 6,
          width: 5,
          height: 9,
          depth: 5,
          x: 5,
          y: 9,
          z: 63,
          topWidth: 2,
          topDepth: 2,
          rotateX: 30,
          rotateY: 60,
          rotateZ: -25,
        },
      },

      // Crown layers - creating depth and richness
      // Bottom layer - largest and darkest
      {
        type: "shape",
        props: {
          color: "#1e5631",
          sides: 16,
          width: 75,
          height: 23,
          depth: 75,
          z: 67,
          topWidth: 54,
          topDepth: 54,
          rotateY: 15,
        },
      },

      // Second layer - medium green
      {
        type: "shape",
        props: {
          color: "#228B22",
          sides: 14,
          width: 69,
          height: 26,
          depth: 69,
          z: 82,
          topWidth: 45,
          topDepth: 45,
          rotateY: -22,
        },
      },

      // Third layer - brighter green
      {
        type: "shape",
        props: {
          color: "#32CD32",
          sides: 12,
          width: 60,
          height: 25,
          depth: 60,
          z: 100,
          topWidth: 36,
          topDepth: 36,
          rotateY: 30,
        },
      },

      // Fourth layer - lighter green
      {
        type: "shape",
        props: {
          color: "#90EE90",
          sides: 10,
          width: 51,
          height: 23,
          depth: 51,
          z: 118,
          topWidth: 27,
          topDepth: 27,
          rotateY: -18,
        },
      },

      // Top crown - brightest
      {
        type: "shape",
        props: {
          color: "#ADFF2F",
          sides: 8,
          width: 36,
          height: 18,
          depth: 36,
          z: 138,
          topWidth: 15,
          topDepth: 15,
        },
      },

      // Crown peak
      {
        type: "shape",
        props: {
          color: "#9ACD32",
          sides: 8,
          width: 21,
          height: 12,
          depth: 21,
          z: 153,
          topWidth: 6,
          topDepth: 6,
        },
      },

      // Foliage clusters for extra detail
      {
        type: "shape",
        props: {
          color: "#228B22",
          sides: 8,
          width: 15,
          height: 9,
          depth: 15,
          x: 18,
          y: -15,
          z: 96,
          topWidth: 7,
          topDepth: 7,
          rotateX: -15,
          rotateY: 40,
          rotateZ: 20,
        },
      },
      {
        type: "shape",
        props: {
          color: "#32CD32",
          sides: 6,
          width: 13,
          height: 11,
          depth: 13,
          x: -21,
          y: 12,
          z: 99,
          topWidth: 6,
          topDepth: 6,
          rotateX: 25,
          rotateY: -50,
          rotateZ: -30,
        },
      },
      {
        type: "shape",
        props: {
          color: "#90EE90",
          sides: 8,
          width: 12,
          height: 7,
          depth: 12,
          x: 15,
          y: 18,
          z: 111,
          topWidth: 5,
          topDepth: 5,
          rotateX: 10,
          rotateY: 35,
          rotateZ: 15,
        },
      },
      {
        type: "shape",
        props: {
          color: "#228B22",
          sides: 6,
          width: 11,
          height: 8,
          depth: 11,
          x: -12,
          y: -18,
          z: 114,
          topWidth: 4,
          topDepth: 4,
          rotateX: -20,
          rotateY: -45,
          rotateZ: 25,
        },
      },

      // Additional foliage to fill crown gaps
      {
        type: "shape",
        props: {
          color: "#1e5631",
          sides: 8,
          width: 16,
          height: 8,
          depth: 16,
          x: 22,
          y: 8,
          z: 85,
          topWidth: 8,
          topDepth: 8,
          rotateX: 15,
          rotateY: 65,
          rotateZ: -10,
        },
      },
      {
        type: "shape",
        props: {
          color: "#32CD32",
          sides: 6,
          width: 14,
          height: 10,
          depth: 14,
          x: -18,
          y: -22,
          z: 88,
          topWidth: 7,
          topDepth: 7,
          rotateX: -25,
          rotateY: -40,
          rotateZ: 35,
        },
      },
      {
        type: "shape",
        props: {
          color: "#228B22",
          sides: 8,
          width: 13,
          height: 9,
          depth: 13,
          x: -8,
          y: 25,
          z: 106,
          topWidth: 6,
          topDepth: 6,
          rotateX: 20,
          rotateY: -25,
          rotateZ: -15,
        },
      },
      {
        type: "shape",
        props: {
          color: "#90EE90",
          sides: 6,
          width: 11,
          height: 6,
          depth: 11,
          x: 8,
          y: -12,
          z: 125,
          topWidth: 4,
          topDepth: 4,
          rotateX: -10,
          rotateY: 30,
          rotateZ: 20,
        },
      },
    ],
  },
] satisfies ShapeNode[];
